### ISSUE TITLE
TimeoutError: Waiting failed: timeout 30000ms exceeded

### ISSUE THREAD

**Issue by WeiqiMaster** [IggsGrey/linkedin-easy-apply-bot#5]
I did some research. I think it’s the selector that failed. Maybe LinkedIn DOM structure changed?

**Comment by IggsGrey** [comment]
Hey @WeiqiMaster  can you share a screenshot of the error log in the console?

**Comment by WeiqiMaster** [comment]
> Hey @WeiqiMaster can you share a screenshot of the error log in the console?

Sure here is the screenshot of the console:
![timeout_error](https://github.com/IggsGrey/linkedin-easy-apply-bot/assets/43047144/853d9398-a44e-496d-9faf-7929c24c9fe4)

And here is some of my config:
![config1](https://github.com/IggsGrey/linkedin-easy-apply-bot/assets/43047144/4263544c-bfba-401b-8699-952a1e7bcde1)
![config2](https://github.com/IggsGrey/linkedin-easy-apply-bot/assets/43047144/db9d2956-f0c6-4ecc-999e-0c13a72df363)

**Comment by IggsGrey** [comment]
Please try out the change on the branch called `fix_broken_application_flow` to know if it works for you

**Comment by IggsGrey** [comment]
https://github.com/IggsGrey/linkedin-easy-apply-bot/pull/7 works for me
