### ISSUE TITLE
  JOB_DESCRIPTION: "^((?!(primeit))(.|[\n\r]))*$",

### ISSUE THREAD

**Issue by ralyodio** [IggsGrey/linkedin-easy-apply-bot#8]
`  JOB_DESCRIPTION: "^((?!(primeit))(.|[\n\r]))*$",`

what does this do? what does "primeit" mean?

**Comment by IggsGrey** [comment]
https://regex101.com/r/yPuhNx/1

"primeit" is likely a class name or some other attribute value on an element. Either that, or an attempt by the initial dev to not match the string "primeit" in the job descriptions

**Comment by NathanWailes** [comment]
IMO you should update the example to just make it clear that a regex is acceptable. That example is confusing.
